spring:
  application:
    name: API-chamados

  datasource:
    url: jdbc:mysql://localhost:3308/chamadados_db
    username: myuser
    password: secretkey
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

aws:
  sns:
    endpoint: http://localhost:4566
    access-key: my-access-key
    secret-key: my-secret-key
    topic-arn: arn:aws:sns:us-east-1:000000000000:chamados